// components/ui/button.tsx
import React from 'react';

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'outline' | 'ghost';
  size?: 'sm' | 'md' | 'lg';
  fullWidth?: boolean;
}

export const Button: React.FC<ButtonProps> = ({ 
  children, 
  variant = 'primary', 
  size = 'md', 
  fullWidth = false,
  className = '',
  ...props 
}) => {
  const baseStyles = "transition-all duration-300 uppercase tracking-widest font-medium rounded-sm flex items-center justify-center";
  
  const variants = {
    primary: "bg-amber-700 hover:bg-amber-800 text-amber-50 disabled:opacity-50 disabled:cursor-not-allowed",
    outline: "border border-amber-700 text-amber-50 hover:bg-amber-900/30 disabled:opacity-50 disabled:cursor-not-allowed",
    ghost: "text-amber-200 hover:text-amber-100 disabled:opacity-50 disabled:cursor-not-allowed"
  };

  const sizes = {
    sm: "px-4 py-2 text-xs",
    md: "px-8 py-3 text-sm",
    lg: "px-10 py-4 text-base"
  };

  const width = fullWidth ? "w-full" : "";

  return (
    <button 
      className={`${baseStyles} ${variants[variant]} ${sizes[size]} ${width} ${className}`}
      {...props}
    >
      {children}
    </button>
  );
};

// frontend/src/components/Button.svelte
<script>
  export let variant = 'primary'; // primary, secondary, outline, danger
  export let size = 'md'; // sm, md, lg
  export let type = 'button';
  export let disabled = false;
  export let loading = false;
  export let fullWidth = false;
  
  const variants = {
    primary: 'bg-text-main text-bg-main hover:bg-text-main/90 shadow-sm',
    secondary: 'bg-accent-lime text-text-main hover:bg-accent-lime/90',
    outline: 'border-2 border-text-main/20 text-text-main hover:border-text-main/40',
    danger: 'bg-red-500 text-white hover:bg-red-600',
  };
  
  const sizes = {
    sm: 'px-3 py-1.5 text-sm',
    md: 'px-4 py-2.5 text-sm',
    lg: 'px-6 py-3 text-base',
  };
  
  $: classes = `
    ${variants[variant]} 
    ${sizes[size]} 
    ${fullWidth ? 'w-full' : ''}
    font-semibold rounded-lg transition-all duration-200
    disabled:opacity-50 disabled:cursor-not-allowed
    active:scale-95
  `;
</script>

<button 
  {type} 
  {disabled}
  class={classes}
  on:click
>
  {#if loading}
    <div class="flex items-center justify-center gap-2">
      <div class="w-4 h-4 border-2 border-current border-t-transparent rounded-full animate-spin"></div>
      <span>Loading...</span>
    </div>
  {:else}
    <slot />
  {/if}
</button>
