// app/login/page.tsx
'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Lotus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

export default function LoginPage() {
  const router = useRouter();
  const [formData, setFormData] = useState({
    email: '',
    password: ''
  });
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      const res = await fetch('/api/auth/login', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(formData)
      });

      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.message || 'Login failed');
      }

      // Store token (basic implementation)
      localStorage.setItem('token', data.token);
      localStorage.setItem('user', JSON.stringify(data.user));

      router.push('/dashboard');
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen grid lg:grid-cols-2 bg-stone-900">
      {/* Visual Side */}
      <div className="hidden lg:flex flex-col justify-center items-center bg-[#2C2926] relative overflow-hidden p-12">
        <div className="absolute inset-0 opacity-10" 
             style={{ backgroundImage: 'url("https://images.unsplash.com/photo-1600334129128-685c5582fd35?auto=format&fit=crop&q=80")', backgroundSize: 'cover', backgroundPosition: 'center' }}>
        </div>
        <div className="relative z-10 text-center max-w-md">
          <div className="mx-auto w-24 h-24 mb-8 text-amber-500/80 flex items-center justify-center">
             <Lotus size={80} strokeWidth={1} />
          </div>
          <h2 className="font-display text-4xl text-amber-50 mb-6">Welcome Back</h2>
          <p className="font-light text-stone-300 text-lg leading-relaxed">
            "To keep the body in good health is a duty... otherwise we shall not be able to keep our mind strong and clear."
          </p>
        </div>
      </div>

      {/* Form Side */}
      <div className="flex flex-col justify-center items-center p-8 bg-stone-900">
        <div className="w-full max-w-md space-y-8">
            <div className="text-center lg:hidden mb-8">
                <Lotus className="mx-auto text-amber-500 mb-4" size={48} />
                <h2 className="font-display text-3xl text-amber-50">Vita Clinic</h2>
            </div>

            <div className="space-y-2">
                <h1 className="font-display text-2xl text-amber-50">Sign In</h1>
                <p className="text-stone-400 font-light">Enter your details to access your wellness dashboard</p>
            </div>

            {error && (
                <div className="p-4 bg-red-900/20 border border-red-900/50 text-red-200 text-sm rounded-sm">
                    {error}
                </div>
            )}

            <form onSubmit={handleSubmit} className="space-y-6">
                <div className="space-y-4">
                    <div className="space-y-2">
                        <label htmlFor="email" className="text-xs uppercase tracking-wider text-stone-400">Email</label>
                        <Input 
                            id="email"
                            name="email"
                            type="email" 
                            placeholder="name@example.com" 
                            value={formData.email}
                            onChange={handleChange}
                            required
                        />
                    </div>
                    <div className="space-y-2">
                        <label htmlFor="password" className="text-xs uppercase tracking-wider text-stone-400">Password</label>
                        <Input 
                            id="password"
                            name="password"
                            type="password" 
                            value={formData.password}
                            onChange={handleChange}
                            required
                        />
                    </div>
                </div>

                <Button fullWidth disabled={loading}>
                    {loading ? 'More gently...' : 'Enter Sanctuary'}
                </Button>
            </form>

            <div className="text-center pt-4">
                <p className="text-stone-400 text-sm">
                    New to Vita? {' '}
                    <Link href="/register" className="text-amber-500 hover:text-amber-400 underline decoration-amber-500/30 underline-offset-4 transition-colors">
                        Begin your journey
                    </Link>
                </p>
            </div>
        </div>
      </div>
    </div>
  );
}

// frontend/src/pages/auth/Login.svelte
<script>
  import { navigate } from 'svelte-routing';
  import { api } from '../../lib/api.js';
  import { user } from '../../stores/auth.js';
  import Button from '../../components/Button.svelte';
  import Input from '../../components/Input.svelte';
  import Card from '../../components/Card.svelte';
  
  let email = '';
  let otp = '';
  let step = 'email'; // email, otp
  let loading = false;
  let error = '';
  
  async function handleSendOTP() {
    if (!email) {
      error = 'Please enter your email';
      return;
    }
    
    loading = true;
    error = '';
    
    try {
      await api.sendOTP(email);
      step = 'otp';
    } catch (err) {
      error = err.message;
    } finally {
      loading = false;
    }
  }
  
  async function handleVerifyOTP() {
    if (!otp) {
      error = 'Please enter the OTP';
      return;
    }
    
    loading = true;
    error = '';
    
    try {
      const response = await api.verifyOTP(email, otp);
      localStorage.setItem('token', response.token);
      localStorage.setItem('user', JSON.stringify(response.user));
      user.set(response.user);
      navigate('/patient/dashboard');
    } catch (err) {
      error = err.message;
    } finally {
      loading = false;
    }
  }
</script>

<div class="min-h-screen bg-bg-main pt-20 px-4">
  <div class="max-w-md mx-auto">
    <!-- Hero Section -->
    <div class="text-center mb-8">
      <div class="inline-flex items-center justify-center w-20 h-20 rounded-full bg-accent-lime/20 mb-4">
        <iconify-icon icon="solar:health-bold" width="40" class="text-text-main"></iconify-icon>
      </div>
      <h1 class="text-4xl font-semibold tracking-tighter-custom mb-2">Welcome Back</h1>
      <p class="text-text-main/60">Access your health records securely</p>
    </div>
    
    <Card padding="loose">
      {#if step === 'email'}
        <div class="space-y-4">
          <h2 class="text-xl font-semibold">Patient Login</h2>
          <p class="text-sm text-text-main/60">Enter your email to receive a one-time password</p>
          
          <Input
            type="email"
            label="Email Address"
            placeholder="you@example.com"
            bind:value={email}
            required
          />
          
          {#if error}
            <div class="p-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-600">
              {error}
            </div>
          {/if}
          
          <Button
            variant="primary"
            fullWidth
            {loading}
            on:click={handleSendOTP}
          >
            Send OTP
          </Button>
          
          <div class="text-center text-sm text-text-main/60">
            Staff member? <a href="/staff-login" class="text-text-main font-medium hover:underline">Login here</a>
          </div>
        </div>
      {:else}
        <div class="space-y-4">
          <h2 class="text-xl font-semibold">Verify OTP</h2>
          <p class="text-sm text-text-main/60">
            We've sent a code to <strong>{email}</strong>
          </p>
          
          <Input
            type="text"
            label="One-Time Password"
            placeholder="Enter 6-digit code"
            bind:value={otp}
            required
          />
          
          {#if error}
            <div class="p-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-600">
              {error}
            </div>
          {/if}
          
          <Button
            variant="primary"
            fullWidth
            {loading}
            on:click={handleVerifyOTP}
          >
            Verify & Login
          </Button>
          
          <button
            on:click={() => step = 'email'}
            class="text-sm text-text-main/60 hover:text-text-main w-full text-center"
          >
            ← Back to email
          </button>
        </div>
      {/if}
    </Card>
    
    <!-- Features -->
    <div class="mt-12 grid grid-cols-3 gap-4">
      <div class="text-center">
        <div class="w-12 h-12 rounded-full bg-accent-green/20 flex items-center justify-center mx-auto mb-2">
          <iconify-icon icon="solar:shield-check-bold" width="24" class="text-accent-green"></iconify-icon>
        </div>
        <p class="text-xs text-text-main/60">Secure</p>
      </div>
      <div class="text-center">
        <div class="w-12 h-12 rounded-full bg-accent-lime/20 flex items-center justify-center mx-auto mb-2">
          <iconify-icon icon="solar:clock-circle-bold" width="24" class="text-text-main"></iconify-icon>
        </div>
        <p class="text-xs text-text-main/60">Real-time</p>
      </div>
      <div class="text-center">
        <div class="w-12 h-12 rounded-full bg-accent-pink/20 flex items-center justify-center mx-auto mb-2">
          <iconify-icon icon="solar:heart-bold" width="24" class="text-accent-pink"></iconify-icon>
        </div>
        <p class="text-xs text-text-main/60">Care</p>
      </div>
    </div>
  </div>
</div>
